format_version: v1.0
configName: classb_api_usage
folderName: classb_api_usage
frameworkPath: C:\Gladis\harmony
processor: PIC32CM5164JH01100
projectName: classb_api_usage
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-JH_DFP\1.1.203\PIC32CM-JH01\atdf\PIC32CM5164JH01100.atdf
